//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class indicadoresDBEntities : DbContext
    {
        public indicadoresDBEntities()
            : base("name=indicadoresDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<canton> canton { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<consulta> consulta { get; set; }
        public virtual DbSet<distrito> distrito { get; set; }
        public virtual DbSet<fecha> fecha { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<respuesta> respuesta { get; set; }
    }
}
